name: Go Fuzz Testing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  fuzz-usaddress:
    name: Fuzz usaddress
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fuzz
      run: |
        go test ./pkg/usaddress/... -fuzz Fuzz -fuzztime 10m

    - name: Report Failures
      if: ${{ failure() }}
      run: |
        find ./pkg/usaddress/testdata/fuzz/ -type f | xargs -n1 tail -n +1 -v
